### ISSUE TITLE
Generic database interface

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-database#12]
> while making db interfaces, I ended up using very similar code for diarization and speaker spotting protocols to the one that you have implemented in the interface for AMI dataset. This made me thinking that may be it would be possible to generalize this code into generic database interface that would work for any database, given the filelists formatted according the pre-defined format.

**Comment by hbredin** [comment]
We could rely on a new file `~/.pyannote/protocol.yml` that would look like this for `REPERE.SpeakerDiarization.Phase2`:

```yaml
REPERE:
  SpeakerDiarization:
    Phase2:
      train: 
        annotation: /path/to/train.rttm
        annotated: /path/to/train.uem
      development: 
        annotation: /path/to/development.rttm
        annotated: /path/to/development.uem
      test: 
        annotation: /path/to/test.rttm
        annotated: /path/to/test.uem
```
