### ISSUE TITLE
Problem loading a custom protocol

### ISSUE THREAD

**Issue by dawei-liang** [pyannote/pyannote-database#37]
Hello,

I am trying leveraging the pre-trained models on my own data. I already followed the instruction to modify the AMI protocol file. However, when I try following the instruction on preparing the protocol on the AMI subset, I kept getting error as: 'KeyError: 'AMI'' and "ValueError: Could not find any protocol for "AMI" database". 

Here are the instruction on the page that I followed:
 
preprocessors = {'audio': FileFinder()}
protocol = get_protocol('AMI.SpeakerDiarization.MixHeadset',
                        preprocessors=preprocessors)

Not sure if it was the directory issue. If so, how can I define the proper directory while calling it? And what is the function FileFinder() used for here?

Thanks for your time!

**Comment by hbredin** [comment]
I just transferred the issue to `pyannote.database` repo.

This seems to be an issue with a malformed or mislocated `database.yml` file.

Can you please share
* the content of the PYANNOTE_DATABASE_CONFIG environment variable? 
   ```bash
   echo $PYANNOTE_DATABASE_CONFIG
   ```
* the content of `~/.pyannote/database.yml` or whichever file returned by the above `echo` line.

**Comment by dawei-liang** [comment]
Thank you very much for your reply! What I got from `echo $PYANNOTE_DATABASE_CONFIG` was:
/home/dawei/research-socialbit/pyannote-audio/tutorials/data_preparation/database.yml

And within the .yaml file I had something like:


```
Databases:
   AMI: /home/dawei/research-socialbit/pyannote-audio/AMI_corpus/amicorpus/*/audio/{uri}.wav
   MUSAN: /home/dawei/research-socialbit/pyannote-audio/AMI_corpus/amicorpus/AMI_corpus/musan/{uri}.wav

Protocols:
   AMI:
      SpeakerDiarization:
         MixHeadset:
           train:
              annotation: /home/dawei/research-socialbit/pyannote-audio/tutorials/data_preparation/AMI/MixHeadset.train.rttm
              annotated: /home/dawei/research-socialbit/pyannote-audio/tutorials/data_preparation/AMI/MixHeadset.train.uem
           development:
              annotation: /home/dawei/research-socialbit/pyannote-audio/tutorials/data_preparation/AMI/MixHeadset.development.rttm
              annotated: /home/dawei/research-socialbit/pyannote-audio/tutorials/data_preparation/AMI/MixHeadset.development.uem
           test:
              annotation: /home/dawei/research-socialbit/pyannote-audio/tutorials/data_preparation/AMI/MixHeadset.test.rttm
              annotated: /home/dawei/research-socialbit/pyannote-audio/tutorials/data_preparation/AMI/MixHeadset.test.uem
```
I also manually checked the return of the  _add_custom_protocols()_  function in the ~/pyannote/database/__init.py__. It seems that the return was none. I noticed that my issue could be fixed if I manually fed the path of the .yaml file to the  _add_custom_protocols()_  function. So I am not pretty sure why it could not detect my protocol automatically?

Sorry I opened another similar issue, it is now closed I think. Thanks for your time!
