### ISSUE TITLE
Using patterns for annotation files

### ISSUE THREAD

**Issue by skubicius** [pyannote/pyannote-database#62]
Is it possible to use patterns for .rttm locations?
For example:
```
Protocols:
  MyDatabase:
    Protocol:
      MyProtocol:
        train:
            uri: lists/train.lst
            speaker: rttms/{uri}.rttm
```

**Comment by hbredin** [comment]
Yes, see the documentation [here](https://github.com/pyannote/pyannote-database#data-loaders).
Use the `_` prefix to turn path into a template:

```yaml
Protocols:
  MyDatabase:
    Protocol:
      MyProtocol:
        train:
            uri: lists/train.lst
            speaker: _rttms/{uri}.rttm
```
