### ISSUE TITLE
Cannot combine several protocols from different databases into one

### ISSUE THREAD

**Issue by tubali12345** [pyannote/pyannote-database#98]
I am trying to combine multiple protocols into one as shown in the [Meta-protocols and requirements] section in the README. I create the following database.yml configuration file with the already existing protocol configuration files (both works fine).
```yaml
Requirements:
  - /path/to/folder/aishell4/database.yml
  - /path/to/folder/ali/database.yml

Protocols:
  CombinedAll:
    SpeakerDiarization:
      MyMetaProtocol:
        train:
          AISHELL4.SpeakerDiarization.Custom: [train, ]
          ALI.SpeakerDiarization.Custom: [train, ]
        development:
          AISHELL4.SpeakerDiarization.Custom: [development, ]
          ALI.SpeakerDiarization.Custom: [development, ]
        test:
          AISHELL4.SpeakerDiarization.Custom: [test, ]
          ALI.SpeakerDiarization.Custom: [test, ]
```
And then trying to call it
```python
from pyannote.database import registry, FileFinder

registry.load_database("path/to/combined/database.yml")
protocol = registry.get_protocol("CombinedAll.SpeakerDiarization.MyMetaProtocol", preprocessors={"audio": FileFinder()})

for file in protocol.train():
    pass
```
But it gives me an error: 
```python
File "/opt/miniconda3/envs/speaker_diar/lib/python3.10/site-packages/pyannote/database/protocol/protocol.py", line 374, in subset_helper
  for file in files:
File "/opt/miniconda3/envs/speaker_diar/lib/python3.10/site-packages/pyannote/database/custom.py", line 317, in subset_iter
  raise ValueError("Missing mandatory 'uri' entry in CombinedAll.SpeakerDiarization.MyMetaProtocol.train")
```

How can this combination of protocols be done?
